model:
  base_learning_rate: 1.5625e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    parameterization: eps
    beta_schedule: linear
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    scale_factor: 1.0
    clip_denoised: false
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 5000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    first_stage_key: video
    cond_stage_key: condition_frames
    cond_stage_trainable: true
    conditioning_key: concat
    cond_stage_config:
      target: ldm.modules.encoders.modules.FramesEmbedder
      params:
        frames: 10
        inner_factor: 5
    image_size: 16
    VQ_batch_size: 256
    channels: 3
    origin_channels: 1
    frame_num:
      cond: 10
      k: 5
    monitor: val/loss_ema
    use_ema: true
    ema_rate: 0.999
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        dims: 2
        image_size: 16
        out_channels: 3
        t_in_channels: 15
        t_out_channels: 5
        model_channels: 96
        attention_resolutions:
        - 2
        - 4
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 96
        dropout: 0.1
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 32
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
data:
  target: main.DataModuleFromConfig
  params:
    batch_size:
      train: 64
      validation: 100
      test: 256
    num_workers: 8
    wrap: false
    train:
      target: data.mydataset.KTH
      params:
        data_dir: /home/ubuntu11/zzc/data/KTH/pred-vdm/processed/train
        frames_per_sample: 15
    validation:
      target: data.mydataset.KTH
      params:
        data_dir: /home/ubuntu11/zzc/data/KTH/pred-vdm/processed/valid
        frames_per_sample: 30
        total_videos: 128
    test:
      target: data.mydataset.KTH
      params:
        data_dir: /home/ubuntu11/zzc/data/KTH/pred-vdm/processed/valid
        frames_per_sample: 40
        total_videos: 256
