lightning:
  callbacks:
    video_logger:
      target: main.VideoLogger
      params:
        batch_frequency: 1
        calculate_video_num: 256
        save_video_num: 8
        increase_log_steps: false
        log_videos_kwargs:
          # steps: 100
          # log_every_t: 20
          # sampler_type: dpmsolver
          # steps: 1000
          # log_every_t: 200
          # sampler_type: ddpm
          steps: 200
          log_every_t: 50
          sampler_type: ddim
  trainer:
    benchmark: true
    max_steps: 400000
    log_every_n_steps: 100
    num_sanity_val_steps: 0
    check_val_every_n_epoch: 200
    gradient_clip_val: 1.0
    accelerator: gpu
    gpus: 0,1
