lightning:
  callbacks:
    video_logger:
      target: main.VideoLogger
      params:
        batch_frequency: 1
        calculate_video_num: 256
        save_video_num: 8
        increase_log_steps: false
  trainer:
    benchmark: true
    max_steps: 200000
    log_every_n_steps: 100
    num_sanity_val_steps: 0
    check_val_every_n_epoch: 200
    accelerator: gpu
    gpus: 0,1
