model:
  base_learning_rate: 2e-06 # 4e-07
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    # it should be ['x0' or 'eps']
    parameterization: eps
    beta_schedule: linear
    linear_start: 0.0001 # 0.0015
    linear_end: 0.02 # 0.0195
    num_timesteps_cond: 1
    log_every_t: 200 # log_every_timestep
    timesteps: 1000
    scale_factor: 0.2
    clip_denoised: True
    
    scheduler_config: 
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        # 2000 warmup steps
        warm_up_steps: [2000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [1.]

    first_stage_key: video
    # cond_stage_key: class_label

    # 1. if     caption, coordinates_bbox
    #               -> batch
    # 2. elif   class_label
    #               -> batch[cond_key]
    # 3. else   image, nix, LR_image, masked_image, segmentation，objects_bbox，depth，bbox_img
    #               -> super().get_input(batch, cond_key).to(self.device)
    
    # cond_stage_trainable: false
    # [None, 'concat', 'crossattn', 'hybrid', 'adm']
    # conditioning_key: crossattn

    # cond_stage_config: __is_first_stage__

    cond_stage_config: __is_unconditional__

    # cond_stage_config:
    #   target: models.optical_flow.opticalflow.OpticalFlowEmbedder
    #   params:

    # cond_stage_config:
    #   target: ldm.modules.encoders.modules.ClassEmbedder
    #   params:
    #     # nn.Embedding(n_classes, embed_dim) n_classes have embed_dims
    #     n_classes: 6
    #     embed_dim: 512
    #     key: class_label

    # cond_stage_config:
    #   target: ldm.modules.encoders.modules.BERTEmbedder
    #   params:
    #     n_embed: 512
    #     n_layer: 16
    #     vocab_size: 8192
    #     max_seq_len: 92
    #     use_tokenizer: false

    # cond_stage_config:
    #   target: torch.nn.Identity

    # cond_stage_config:
    #   target: ldm.modules.encoders.modules.SpatialRescaler
    #   params:
    #     n_stages: 2
    #     in_channels: 182
    #     out_channels: 3

    # cond_stage_config:
    #   target: taming.models.dummy_cond_stage.DummyCondStage
    #   params:
    #     conditional_key: objects_bbox

    # cond_stage_config:
    #   target: taming.modules.misc.coord.CoordStage
    #   params:
    #     n_embed: 1024
    #     down_factor: 16

    # cond_stage_config:
    #   target: taming.models.dummy_cond_stage.DummyCondStage
    #   params:
    #     conditional_key: objects_bbox

    image_size: 16
    channels: 3
    frame_num:
      train_total: 15
      valid_total: 20
      test_total: 50
      cond: 10
      pred: 5
    monitor: val/loss_ema

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        dims: 2
        image_size: 16
        in_channels: 45
        out_channels: 45
        model_channels: 224
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 64
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    
    

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 
      train: 64
      validation: 100
      test: 256
    num_workers: 8
    wrap: false
    train:
      target: taming.data.mydataset.KTH
      params:
        type: train
        size: 64
    validation:
      target: taming.data.mydataset.KTH
      params:
        type: valid
        size: 64
    test:
      target: taming.data.mydataset.KTH
      params:
        type: test
        size: 64

lightning:
  callbacks:
    video_logger:
      target: main.VideoLogger
      params:
        # we do videologger (save local, and upload wandb) when training and validation, which step % [batch_frequency] == 0
        # ps: it should run and set it again or estimated it (min batch_frequency = ceil(training dataset / training batchsize / gpus) )
        batch_frequency: 730 # it means 146 batches in a epoch * 5
        max_videos: 4
        increase_log_steps: False

  trainer:
    benchmark: True
    # accumulate_grad_batches: 2
    # Stop training after training step up to [max_steps]. Disabled by default (-1), it will go on forever until interrupted
    max_steps: 40000
    # log_steps for train_loss (because its log_dict\log is on_step=True), default (50),
    log_every_n_steps: 50
    # Sanity check runs n validation batches before starting the training routine. Set it to -1 to run all batches in all validation dataloaders. Default: 2.
    num_sanity_val_steps: 0